### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by odesey** [openvenues/node-postal#11]
Is there anyway to change the format of the address being returned by the parser? For example when an address is parsed I get back an array looking like this:
```javascript
  [ { value: '8809', component: 'house_number' },
  { value: 'madison ave', component: 'road' },
  { value: 'cleveland', component: 'city' },
  { value: 'oh', component: 'state' },
  { value: '44102-2738', component: 'postcode' },
  { value: 'usa', component: 'country' } ]

[ { value: '2511', component: 'house_number' },
  { value: 'w genesee st', component: 'road' },
  { value: 'syracuse', component: 'city' },
  { value: 'ny', component: 'state' },
  { value: '13219-1549', component: 'postcode' },
  { value: 'usa', component: 'country' } ]
```
This is making it very difficult to reconstruct the address and send it to a database. Is there anyway to format the data like:

```json
house_number: '123',
street: 'Some St'
city: 'CA'
postalcode: '12345'
```

Thanks for the great package.

**Comment by thatdatabaseguy** [comment]
By converting the output to an object/dictionary/hash we would lose the order of the components, as well as the ability to handle multiple values for the same component (in the US this is not as prevalent but in some countries like the UK, India, Malaysia, etc. it is more common).

You can certainly format it that way as a post-processing step if you want, for example:

```javascript
var postal = require('node-postal');

var components = postal_parse('8809 Madison Ave, Cleveland, OH, 44102-2738, USA');
var unique_components = {};
for (var i = 0; i < components.length; i++) {
    var c = components[i];
    if (!(unique_components.hasOwnProperty(c.component))) { 
        unique_components[c.component] = c.value;
    }
}
```

**Comment by odesey** [comment]
Thanks for the quick response! Your suggestion solved my issue. I notice you are using the `postal_parse` method. This isn't in the documentation, is there a list of all the methods available and what they should be used for?

Thanks again.

**Comment by thatdatabaseguy** [comment]
Oh, wrong binding, edited. It's supposed to be ```postal.parser.parse_address```.

**Comment by odesey** [comment]
Got it, thanks for the help again.
