### ISSUE TITLE
Can't find bindings expand

### ISSUE THREAD

**Issue by stessarin** [openvenues/node-postal#12]
Hi we have facing issue on make node-postal working. All 3+Gb of data has been downloaded  and postal c library works perfectly so we can parse address via command line utility. 

Sadly we spent 3+ hours to make node-postal working with no luck.

We are working on Ubuntu 16.4.0.2
Node 7.7.2

this is the result of node:

`node main.js
/home/ufficio/libpostal/node/node_modules/bindings/bindings.js:90
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/ufficio/libpostal/node/node_modules/node-postal/build/expand.node
 → /home/ufficio/libpostal/node/node_modules/node-postal/build/Debug/expand.node
 → /home/ufficio/libpostal/node/node_modules/node-postal/build/Release/expand.node
 → /home/ufficio/libpostal/node/node_modules/node-postal/out/Debug/expand.node
 → /home/ufficio/libpostal/node/node_modules/node-postal/Debug/expand.node
 → /home/ufficio/libpostal/node/node_modules/node-postal/out/Release/expand.node
 → /home/ufficio/libpostal/node/node_modules/node-postal/Release/expand.node
 → /home/ufficio/libpostal/node/node_modules/node-postal/build/default/expand.node
 → /home/ufficio/libpostal/node/node_modules/node-postal/compiled/7.7.2/linux/x64/expand.node
    at bindings (/home/ufficio/libpostal/node/node_modules/bindings/bindings.js:87:9)
    at Object.<anonymous> (/home/ufficio/libpostal/node/node_modules/node-postal/index.js:3:32)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ufficio/libpostal/node/main.js:2:14)
`

thanks a lot

**Comment by thatdatabaseguy** [comment]
Could not reproduce this. Just built libpostal and node-postal in a Docker container for Ubuntu 16.04 with Node 7.7.2 in a few minutes with no issues.

Here are the exact steps (this was as root so some commands need sudo):

```shell
apt-get update -y
apt-get install curl libsnappy-dev autoconf automake libtool pkg-config git-core build-essential libssl-dev
git clone https://github.com/openvenues/libpostal
cd libpostal
./bootstrap.sh
./configure --datadir=$(pwd)/data
make
make install
cd ..
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
source ~/.bashrc
nvm install 7.7.2
npm install -g node-gyp
npm install openvenues/node-postal
```

After running these, tested both parser and expansion, and everything worked fine.

Try deleting the whole installation and starting over from scratch using the above steps.

**Comment by stessarin** [comment]
After a clean installation it worked without problems, thanks! Although we had to install node_modules in the node_postal folder.
