### ISSUE TITLE
npm test fail on "should handle non-ASCII addresses correctly from Node"

### ISSUE THREAD

**Issue by DamienMetzger** [openvenues/node-postal#2]
Hello, !

I got a failed test when running npm test. The 6 others are OK.
Ubuntu 15.04
Node v4.2.6
node-postal 0.3.0 (just cloned)

> node-postal@0.3.0 test /root/test/node-postal
> mocha ./test

  expand
    expand_address
      ✓ should correctly expand a US address
      ✓ should correctly dedupe equivalent addresses
{ _items: 
   [ 'friedrichstrasse 128 berlin germany',
     'friedrich strasse 128 berlin germany' ] }
      1) should handle non-ASCII addresses correctly from Node

  parser
    parse_address
      ✓ should parse a US address
      ✓ should parse a venue and state
      ✓ should parse house/apt style house_number
      ✓ should parse different comma styles correctly

  6 passing (22ms)
  1 failing

  1) expand expand_address should handle non-ASCII addresses correctly from Node:

      AssertionError: false == true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/index.test.js:21:13)

npm ERR! Test failed.  See above for more details.

Thank you!

**Comment by thatdatabaseguy** [comment]
Hi Damien, thanks for the detailed report. The NodeJS tests needed to be updated to reflect a recent change in libpostal. Everything should pass if you pull latest.

**Comment by DamienMetzger** [comment]
Thank you, all tests are passing now :)

**Comment by thatdatabaseguy** [comment]
Great! There's also now continuous integration set up here: https://travis-ci.org/openvenues/node-postal. Tested on Node 0.10 and up.
