### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by tblobaum** [openvenues/node-postal#38]
Hi, thanks for making node-postal. It seems to be the best option short of paying for a monthly subscription. However, the keys returned with `parse_address` are not documented. Is there a list of all of them somewhere? It looks like they aren't all in the tests, either.

**Comment by missinglink** [comment]
They are documented here? https://github.com/openvenues/libpostal#parser-labels

**Comment by tblobaum** [comment]
@missinglink okay thank you
