### ISSUE TITLE
Is this project dead??

### ISSUE THREAD

**Issue by tngflx** [openvenues/node-postal#40]
no maintainer since 2021??

**Comment by nvkelso** [comment]
@missinglink or @orangejulius to comment?

**Comment by missinglink** [comment]
This project is maintained, as you can see by us commenting within two hours of this issue being opened.

The API itself is stable and doesn't require active development, it also requires very little maintenance.

**Comment by tngflx** [comment]
ahh isee. thanks for answering.

**Comment by tngflx** [comment]
it can only run on linux ? no windows?
