### ISSUE TITLE
Publish node-postal to NPM registry

### ISSUE THREAD

**Issue by heikkipora** [openvenues/node-postal#5]
I would really love to see `node-postal` published to the NPM registry. Any changes on doing that ?

The problem is, other projects now need to depend on `node-postal` as a github dependency in their package.json and that really doesn't work in offline environments (using `npm-mirror` or similar).

I'm available for assistance if needed.

**Comment by orangejulius** [comment]
Yup, @thatdatabaseguy we would love this for Pelias. We're happy to have one of us added as a maintainer of this repo to take care of that if you'd like. I've worked with a few native Node modules now and would gladly set things up.

**Comment by thatdatabaseguy** [comment]
Et voila! https://www.npmjs.com/package/node-postal. Let me know if there are any issues.

@orangejulius I thought I remembered someone over there mentioning that the underlying C lib needed to be bundled with node-postal. Is that still a thing or was that idea just to have a one-command install?
