### ISSUE TITLE
ImportError: No module named compiler.ast

### ISSUE THREAD

**Issue by bhanuc** [openvenues/node-postal#9]
```root@gdg:~/courier-bhanuc# npm install openvenues/node-postal --save

> node-postal@0.3.0 install /root/courier-bhanuc/node_modules/node-postal
> (node-gyp rebuild) || (exit 0)

Traceback (most recent call last):
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 13, in <module>
    import gyp
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 8, in <module>
    import gyp.input
  File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 5, in <module>
    from compiler.ast import Const
ImportError: No module named compiler.ast
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-45-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/courier-bhanuc/node_modules/node-postal
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```
any help on  the issue would be great. Please comment here if can help

**Comment by thatdatabaseguy** [comment]
Either gcc isn't installed (```apt-get install gcc``` or ```yum install gcc```) or node-gyp isn't installed (```npm install -g node-gyp```).

For this and other issues that are not specific to libpostal/node-postal, Google is the best resource.

**Comment by bhanuc** [comment]
gcc and node-gyp are both present. The error is returned when running 
```npm install openvenues/node-postal```
Error got fixed when I downgraded my node to version 4.2.6

**Comment by thatdatabaseguy** [comment]
That error is about node-gyp itself. Nothing in the traceback indicates that it originated in node-postal or libpostal (npm install [anything] can produce any number of errors but it doesn't always mean that there's a problem with the library being installed).

node-postal is [tested on Node 6](https://github.com/openvenues/node-postal/blob/master/.travis.yml#L3) (on Ubuntu anyway). It may be that either the version of node-gyp or the version of Python, on which node-gyp depends, needs to be upgraded for Node 6.

**Comment by bhanuc** [comment]
cool will close it then. Thanks
